apiVersion: v1
kind: Pod
metadata:
        name: test
        namespace: logging
spec:
        schedulerName: customScheduler
        containers:
                - name: redis
                  image: redis
