apiVersion: v1
kind: Pod
metadata:
        name: test
        namespace: default
spec:
        schedulerName: testScheduler
        containers:
                - name: redis
                  image: redis
